name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          npm install
          npm install --save-dev @types/aws-serverless-express
          npm run build

      - name: Empaquetar función para Lambda
        run: |
          mkdir -p dist
          cp package.json dist/
          cp -r node_modules dist/
          cp dist/src/lambda.js dist/
          echo "PORT=4000" > dist/.env
          cd dist
          zip -r ../lambda.zip .

      - name: Desplegar en Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          zip_file: lambda.zip
